
[xenonextras]

	[xenonextras.general]
		fpsDisplay = "OFF"
		fpsDisplaySystem = "OFF"

	[xenonextras.others]
		#Configure if borderless fullscreen option should be attached to F11 or replace vanilla fullscreen
		#Allowed Values: ATTACH, REPLACE, OFF
		borderlessAttachModeOnF11 = "OFF"