name = "Hammer"
author = "WaffleIBOT"
version = "1.14.0+1.21.5.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e9ed3deef2ee2b8c1e4b17dce2f570fdabd005c87a5cb20560a333236e0cf33"

[versions]
minecraft = "1.21.5"
neoforge = "21.5.44-beta"
