name = "Hammer"
author = "WaffleIBOT"
version = "1.16.0+1.21.5.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f5b7937ad403f7d1a46fab65165c849491b0ec881d4194b5d870754d9d2bbb4"

[versions]
minecraft = "1.21.5"
neoforge = "21.5.95"
