name = "Hammer"
author = "WaffleIBOT"
version = "1.16.0+1.21.5.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9685600d257da6713f330d786a44ce7ec2bb75fa7cfe37ccffbf8cfb448b1fd7"

[versions]
minecraft = "1.21.5"
neoforge = "21.5.95"
