name = "Hammer"
author = "WaffleIBOT"
version = "1.15.0+1.21.5.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "450e7acf069c57285f00a20cbb5861662405b2b213308b1cacbfe9527a77a548"

[versions]
minecraft = "1.21.5"
neoforge = "21.5.63-beta"
