name = "Hammer"
author = "WaffleIBOT"
version = "1.20.0+26.1.2.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93c335e244682e1168e00e79c17fd9ed0d465ec61149d1e6e72063ab029cce6c"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.76"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
