name = "Hammer"
author = "WaffleIBOT"
version = "1.17.0+1.21.11.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c9a57ceff2c4b20e9b487ca1d21f825926fac46446480a4e6efa3957be0371c"

[versions]
minecraft = "1.21.11"
neoforge = "21.11.26-beta"
