name = "Hammer"
author = "WaffleIBOT"
version = "1.19.1+1.21.11.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba6b4b8c764bee2c3c7e78b5ed22e302b9cab017a8262a49fc0a64e9a188224c"

[versions]
minecraft = "1.21.11"
neoforge = "21.11.42"
