name = "Hammer"
author = "WaffleIBOT"
version = "1.19.1+1.21.11.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "437c1599c4dead6c718cde6b0f371e77c690230c5300605d34718a6d5ccb834d"

[versions]
minecraft = "1.21.11"
neoforge = "21.11.42"
