name = "Hammer"
author = "WaffleIBOT"
version = "1.20.0+1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2d751cc955ddd2cb28a5e90bb556e65ee3446bd723119b2bb51ccc61d76cf11"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = ["1.21"]
