name = "Hammer"
author = "WaffleIBOT"
version = "1.17.2+1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bdc2e413fed3ee8815988629645fe4d63d74b29f65c86fed216b4d1d19e558b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"

[options]
acceptable-game-versions = ["1.21"]
