name = "Hammer"
author = "WaffleIBOT"
version = "1.13.7+1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66e52e32e801b40b6b98cfe020e40eb19b5a4086e3dbe525942ad905c4491e9e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.117"

[options]
acceptable-game-versions = ["1.21"]
