name = "Hammer"
author = "WaffleIBOT"
version = "1.16.0+1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8eb5649bf2b6686cdb7ae991aac1fb0ca27d8d1935395a7278acb3fea1143af7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"

[options]
acceptable-game-versions = ["1.21"]
