name = "Hammer"
author = "WaffleIBOT"
version = "1.14.0+1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "248020b91740b493305411dee6924223c1ca5b3fc1fbfbcc733214306e5fa713"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.141"

[options]
acceptable-game-versions = ["1.21"]
