name = "Hammer"
author = "WaffleIBOT"
version = "1.16.0+1.21.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b779b7b2065e2712386c12d3c88c48baf9e1293323c42fb4a10eef1e7cf73a80"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.193"

[options]
acceptable-game-versions = ["1.21"]
