name = "Hammer"
author = "intergrav, WaffleIBOT"
version = "1.18.0+1.18.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b59cecc5a36c16bd4830615858ec3d76172be3cf46c1b30f2fe6abd03b3f905d"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
