name = "Hammer"
author = "intergrav, WaffleIBOT"
version = "1.18.0+1.19.2.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f134a495181529b6f94bca27a13d82c9e77d68017f9388ade61d642ee5a3e70f"

[versions]
forge = "43.5.2"
minecraft = "1.19.2"
