name = "Hammer"
author = "WaffleIBOT"
version = "1.16.0+1.21.10.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41531b78ef01518db11f659fee33c4dcdcc3b6a29947febaee3fc8a8fbf96086"

[versions]
minecraft = "1.21.10"
neoforge = "21.10.17-beta"
