name = "Hammer"
author = "WaffleIBOT"
version = "1.18.0+1.21.10.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7950ed2b3450c634a84bf3c9fb174e6deac5645f0bf97daef1387fa0b7633c35"

[versions]
minecraft = "1.21.10"
neoforge = "21.10.64"
