name = "Hammer"
author = "WaffleIBOT"
version = "1.16.0+1.21.10.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5dfedf4d430da2fa9dc702f6faeef914cc14ce18e27abc7b751f593b3ca5d00"

[versions]
minecraft = "1.21.10"
neoforge = "21.10.39-beta"
