name = "Hammer"
author = "WaffleIBOT"
version = "1.20.0+26.2.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4405512322dc0ba7561d2ca42ae2a2271f1c4f301adb7dfbc7596bea2966b2c8"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.6-beta"
