name = "Hammer"
author = "WaffleIBOT"
version = "1.20.0+26.2.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a89ac4f7725ac1c1d4e8d64fe3dedf5660b1162bfc7bdaeaf33bad4d7bbdffde"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.7-beta"
