name = "Hammer"
author = "WaffleIBOT"
version = "1.18.0+26.1.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc4b0b18ef1b884cd567e006f4e5a159d651fab7243b46dcda87368625854c1f"

[versions]
minecraft = "26.1.1"
neoforge = "26.1.1.1-beta"

[options]
acceptable-game-versions = ["26.1"]
