name = "Hammer"
author = "WaffleIBOT"
version = "1.19.0+1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08f82f0a30f7c3a6c29a210cac141f87211e4bb508070935e68f5b7d4fd017e8"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
