name = "Hammer"
author = "WaffleIBOT"
version = "1.20.0+1.20.1.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "574e69e9e7ae9da75dad5b546118ed3166b2b8079d00b816a5dc316751772130"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
