name = "Hammer"
author = "WaffleIBOT"
version = "1.16.0+1.21.8.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ed5a38dc5dcfe866b6c6f1a52472fd4a4ce39d5b3ce72b7da2ea4eaffcdc127"

[versions]
minecraft = "1.21.8"
neoforge = "21.8.47"
