name = "Hammer"
author = "WaffleIBOT"
version = "1.16.0+1.21.8.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5e2e1f770e9d860327f1be701843420054fa16237b4a8ac0dd4de22c29e2226"

[versions]
minecraft = "1.21.8"
neoforge = "21.8.47"
