name = "Hammer"
author = "WaffleIBOT"
version = "1.16.0+1.21.8.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65684b6ee434421cf989161077b66f6c38317cba21ac86d108b15d63959bab65"

[versions]
minecraft = "1.21.8"
neoforge = "21.8.47"
