name = "Hammer"
author = "WaffleIBOT"
version = "1.18.0+26.1.neoforge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "faf54f2751404f92ec42d371f28b95d325f01482c57bb14c2ba1ba13ca2e61d4"

[versions]
minecraft = "26.1"
neoforge = "26.1.0.1-beta"
